### PR TITLE
Feature bucketstats

### PR DESCRIPTION
**Pull request by charmster**
The bucketstats package has several goals:
* make it very easy to define statistics, collect them, and report them
* support different types of statistics, including bucketized statistics
* collect statistics with low CPU overhead

Statics are placed in a statistics groups for ease of use and reporting.  bucketstats support several types of statistics: Total, Average, and Bucket.

If a statistic to track is, say, object PUT time then a Total type statistic will track the total time spent in all PUTs; the Average type statistic will track the total time spent in PUTs, the number of PUTs, and the average time per PUT.  A Bucket type statistic will track everything that Average statistic does and will also track the distribution of write times by grouping them into buckets and incrementing the count for the bucket that the PUT time maps to.  Tracking the distribution of PUT times allows a histogram of PUT times to be created.

This pull request also modifies the swiftclient package to use bucketstats to track pretty much every statistic currently tracked using the swiftstack stats package.

This pull request could benefit from a review at several different levels:
1) a review of the implementation (mostly in bucketstats/api.go and bucketstats/impl.go)
2) a review of the API (defined in bucketstats/api.go, but its probably better to look at the API in use in the changes to swiftclient and httpserver, which can be found in the changes to code in the httpserver and swiftclient directories (this is the commit that made those changes: https://github.com/swiftstack/ProxyFS/commit/72b7d1c7bcf2e21a2680fd788a602f7aaf87cd48)
3) A review of the statistics in swiftclient tracked by bucketstats

### CODE REVIEW

**Comment by charmster** [comment]
Here are the statistics currently collected for swiftclient and their output format.  Note the power of 2 notation to indicate bucket sizes 1024 or larger (i.e. 2^17 mean 131,072).

There are different possible output formats.
```
swift@swift-runway[ProxyFS] curl localhost:15346/stats 

proxyfs.swiftclient.AccountDeleteUsec avg:0 count:0 total:0
proxyfs.swiftclient.AccountGetUsec avg:0 count:0 total:0
proxyfs.swiftclient.AccountHeadUsec avg:0 count:0 total:0
proxyfs.swiftclient.AccountPostUsec avg:0 count:0 total:0
proxyfs.swiftclient.AccountPutUsec avg:0 count:0 total:0
proxyfs.swiftclient.ContainerDeleteUsec avg:0 count:0 total:0
proxyfs.swiftclient.ContainerGetUsec avg:0 count:0 total:0
proxyfs.swiftclient.ContainerHeadUsec avg:17471 count:1 total:17471 2^14:1
proxyfs.swiftclient.ContainerPostUsec avg:24803 count:8395 total:208222901 2^13:790 2^14:5919 2^15:696 2^16:935 2^17:51 2^18:4
proxyfs.swiftclient.ContainerPutUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectContentLengthUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectCopyUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectDeleteUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectGetUsec avg:8437 count:220 total:1856180 2^12:31 2^13:181 2^14:8
proxyfs.swiftclient.ObjectGetBytes avg:3441 count:220 total:757219 128:1 256:10 512:58 2^10:74 2^11:6 2^12:0 2^13:70 2^14:1
proxyfs.swiftclient.ObjectHeadUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectLoadUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectLoadBytes avg:0 count:0 total:0
proxyfs.swiftclient.ObjectReadUsec avg:0 count:0 total:0
proxyfs.swiftclient.ObjectReadBytes avg:0 count:0 total:0
proxyfs.swiftclient.ObjectTailUsec avg:8735 count:1 total:8735 2^13:1
proxyfs.swiftclient.ObjectTailBytes avg:1091 count:1 total:1091 2^10:1
proxyfs.swiftclient.ObjectNonChunkedFreeConnection avg:136 count:16928 total:2302208 128:16928
proxyfs.swiftclient.ObjectPutCtxtFetchUsec avg:196 count:8311 total:1631053 16:1 32:32 64:1883 128:3224 256:2641 512:485 2^10:34 2^11:6 2^12:3 2^13:2
proxyfs.swiftclient.ObjectPutCtxtFreeConnection avg:545 count:8311 total:4529495 512:8311
proxyfs.swiftclient.ObjectPutCtxtBytesPut total:16622
proxyfs.swiftclient.ObjectPutCtxtCloseUsec avg:40251 count:8311 total:334528073 2^13:16 2^14:2869 2^15:3687 2^16:1272 2^17:460 2^18:6 2^19:1
proxyfs.swiftclient.ObjectPutCtxtReadBytes avg:0 count:0 total:0
proxyfs.swiftclient.ObjectPutCtxtSendChunkUsec avg:87 count:16622 total:1455134 16:1986 32:4030 64:5272 128:4342 256:876 512:94 2^10:14 2^11:4 2^12:3 2^13:1
proxyfs.swiftclient.ObjectPutCtxtSendChunkBytes avg:613 count:16622 total:10197597 128:8311 256:0 512:0 2^10:8311
proxyfs.swiftclient.ObjectPutCtxtBytes avg:1091 count:8311 total:9067301 2^10:8311
proxyfs.swiftclient.AccountDeleteFailure total:0
proxyfs.swiftclient.AccountGetFailure total:0
proxyfs.swiftclient.AccountHeadFailure total:0
proxyfs.swiftclient.AccountPostFailure total:0
proxyfs.swiftclient.AccountPutFailure total:0
proxyfs.swiftclient.ContainerDeleteFailure total:0
proxyfs.swiftclient.ContainerGetFailure total:0
proxyfs.swiftclient.ContainerHeadFailure total:0
proxyfs.swiftclient.ContainerPostFailure total:0
proxyfs.swiftclient.ContainerPutFailure total:0
proxyfs.swiftclient.ObjectContentLengthFailure total:0
proxyfs.swiftclient.ObjectDeleteFailure total:0
proxyfs.swiftclient.ObjectGetFailure total:0
proxyfs.swiftclient.ObjectHeadFailure total:0
proxyfs.swiftclient.ObjectLoadFailure total:0
proxyfs.swiftclient.ObjectReadFailure total:0
proxyfs.swiftclient.ObjectTailFailure total:0
proxyfs.swiftclient.ObjectPutCtxtFetchFailure total:0
proxyfs.swiftclient.ObjectPutCtxtCloseFailure total:0
proxyfs.swiftclient.SwiftAccountDeleteUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountGetUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountHeadUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountPostUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountPutUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerDeleteUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerGetUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerHeadUsec avg:17471 count:1 total:17471 2^14:1
proxyfs.swiftclient.SwiftContainerPostUsec avg:24803 count:8395 total:208222901 2^13:790 2^14:5919 2^15:696 2^16:935 2^17:51 2^18:4
proxyfs.swiftclient.SwiftContainerPutUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectContentLengthUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectDeleteUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectGetUsec avg:8437 count:220 total:1856180 2^12:31 2^13:181 2^14:8
proxyfs.swiftclient.SwiftObjectHeadUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectLoadUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectReadUsec avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectTailUsec avg:8735 count:1 total:8735 2^13:1
proxyfs.swiftclient.SwiftObjectPutCtxtFetchUsec avg:196 count:8311 total:1631053 16:1 32:32 64:1883 128:3224 256:2641 512:485 2^10:34 2^11:6 2^12:3 2^13:2
proxyfs.swiftclient.SwiftObjectPutCtxtCloseUsec avg:40251 count:8311 total:334528073 2^13:16 2^14:2869 2^15:3687 2^16:1272 2^17:460 2^18:6 2^19:1
proxyfs.swiftclient.SwiftAccountDeleteRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountGetRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountHeadRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountPostRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftAccountPutRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerDeleteRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerGetRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerHeadRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerPostRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftContainerPutRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectContentLengthRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectDeleteRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectGetRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectHeadRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectLoadRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectReadRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectTailRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectPutCtxtFetchRetryOps avg:0 count:0 total:0
proxyfs.swiftclient.SwiftObjectPutCtxtCloseRetryOps avg:0 count:0 total:0
```

**Review by edmc-ss — APPROVED** [review]
This looks awesome, Craig!

I only have three comments:

ONE

The name collision of the term "stats" is unfortunate. The package stats was so-named because it sends statistics to statsd :-). Meanwhile, Prometheus uses a "pull" (as in "polling") model and looks for a web page named "/metrics" though this is, of course, settable. I chose to just make things simplest for Prometheus folks used to "/metrics".

Your new bucketstats are, to my view, GETable via the "/stats" path. Wish we didn't have this name collision.

TWO

The above kind of begs the question of why we wouldn't want these same bucketstats visible to statsd. I believe you & Joe spoke about this the other day.

Check out the code in stats/sender.go for what is going on there to get the stats over to statsd. Perhaps you could leverage that mechanism (or, rather, cloning the purpose of it but doing it in the way best fitting the way bucketstats are represented - quite different from the raw counters currently being sent to statsd).

Similarly, I would think we'd want Prometheus to be able to see these stats.

THREE

The bucketstats as applied to package swiftclient is perfect. As for where else we might like to instrument, I guess "at the top" (e.g. package fs)? This might provide a nice contrast between the stuff at the bottom (package swiftclient) for those operations that have a 1-to-1 correspondence, but they very rarely do.

**Comment by edmc-ss** [comment]
So I kind of lied... about me having only three comments... here's a fourth:

FOUR

Gerard, our resident WebUI advocate, will want to improve upon the Content-Type: text/plain fixed response in doGetOfStats()... In the case of curl clients, what's returned is perfect. But for browsers, we'll probably want text/html content... complete with the fancy boilerplate "wrappers". Probably the simplest example is "/metrics". Don't worry... that selection tabs thing at the top that allows the user to subset the output is totally client (i.e. JavaScript) side stuff... the httpserver just sends the whole thing (as JSON btw). The doGetOfMetrics() func just above where you placed doGetOfStats() provides a simple template from which to clone.

**Comment by orion** [comment]
I just have one comment on @edmc-ss 's review.  Regarding comment #2, let's review the stats and their cardinality and then decide what to export to statsd.  Every stat we emit costs some storage on customer's controllers.  This may or may not be an issue, but let's consider it, maybe with @dbishop.

Oh, and regarding comment #4, Ed, you should never declare the number of comments ahead of time!  You're only setting yourself up for failure!

**Comment by dbishop** [comment]
re: #2 let's talk about it IRL (heading in shortly); generally, you probably want to do _one_ of push or pull collection and trying to mix this is probably a bad idea; statsd is not magic, it's just one way to get stats to somthing that wants them.  We push statsd to `collectd` and `collectd` also polls for some stats, so SwiftStack can handle either.  If Prometheus only pulls and it's important, then just make stats that can be pullable (pollable) pullable and be done w/it.  No need to shoehorn statsd where it doesn;t fit.  Then we'd make collectd hit the local `/metrics` endpoint and send metrics we want into carbon/graphite/whisper.  BAM!

**Review by bschatz-swift — APPROVED** [review]
Looks good to me

**Comment by charmster** [comment]
I'm trying to write a reply to all of the above comments ...

package stats -- i'd like to see the package `proxyfs/stats` retired in favor of `proxyfs/bucketstats` for a couple of reasons (primarily excessive CPU consumption and lack of encapsulation).  but doing that requires that bucketstats supply all or mostly all of the statistics reported by stats, which i didn't want to tackle in a first iteration -- minimum viable product and all that ...

Prometheus/statsd integration -- i haven't looked into this at all.  its's obviously desirable, but see the above comment about a "minimum viable product".  it can be added later.

statistics to collect and memory consumption -- both @orion and @dbishop seem interested in this, and its an important consideration.  the `statsbucket.BucketStatLogRoot2Round` statistics type has 128 buckets, each of which requires 4 bytes for a uint32.  _that's 512 bytes per statistic of this type_ (and, arguably, i should have made this 8 bytes for a uint64 for a total of 1024 bytes).  that's not small, but its not huge, either (the API has provisions to limit the number of buckets used for a type to less than this maximum, but the current code does not implement that optimization).

more importantly, if you're storing a time-series samples of these statistics, _each `BucketLogRoot2Round` statistic needs 512 bytes per statistic per sample_ -- more or less, depending on the way the statistics are stored -- that's worth discussing.

**Pull request merged**
