### PR TITLE
Clean up Makefile... no longer checks for armv71 nor "distro"

### PR DESCRIPTION
**Pull request by edmc-ss**

### CODE REVIEW

**Comment by edmc-ss** [comment]
Here is the cleaned up Makefile for you... please merge to development if/when you approve...

**Comment by edmc-ss** [comment]
@gerardgine = I assume you have resolved the flaky TestStopwatch() failures in go test utils, right?
I'm re-running this to get the Unit Test Pass indication for you :-).

**Comment by edmc-ss** [comment]
Ok... that passed... I'll just merge this now myself. You'll want to git checkout development; git pull; git checkout <your-branch>;git rebase -i development

**Comment by edmc-ss** [comment]
Better yet - I have to get on the road. Can you merge it @gerardgine ?

**Review by gerardgine — APPROVED** [review]

**Pull request merged**
