### PR TITLE
Update the cityhash package to its new location.

### PR DESCRIPTION
**Pull request by creachadair**
This package is being rehomed from bitbucket.org to github.com.
This commit updates the glide lock and import paths.
The version number and commit hash have changed to reflect the import path change, but there is
otherwise no change to the package API.

N.B.: A local invocation of `regression_test.py` fails at the head of the `development` tip from which this PR was forked, following the instructions in the README. It's possible I am missing some other necessary setup detail, but in any case this change should not materially affect the correctness (or otherwise) of the program.

### CODE REVIEW

**Comment by edmc-ss** [comment]
This looks great - thanks for the PR!

I'll get the merge hooks to pass and merge it soon.

**Comment by creachadair** [comment]
The PR build looks clean, but I'm not sure how to trigger the other expected branch build. Do I need to do something specific to make that eligible?

**Comment by edmc-ss** [comment]
Yeah, I don't know what happened to Travis-CI there.
In any event, I need to rebase it and also wanted to clean up the other files now obsolete, so that should kick off a fresh Travis-CI pair...

**Comment by creachadair** [comment]
I rebased against your commits on `development` already, if that helps. The current state of the PR reflects the changes from 7667d847.

**Comment by edmc-ss** [comment]
So it looks like some of the settings we have on particularly the development branch of the swiftstack/ProxyFS repo may have gotten in the way.

In any event, here's what I did:
```
git checkout development
git pull
git checkout -b creachadair-enhubbenate development
git pull https://github.com/creachadair/ProxyFS.git enhubbenate
git push -u origin creachadair-enhubbenate
```
This created the creachadair-enhubbenate branch that I then converted to PR 324 (https://github.com/swiftstack/ProxyFS/pull/324)... and that kicked off the two Travis-CI jobs running now. I'll merge shortly... and I guess we could close *this* PR.

Please excuse my novice GitHub knowledge here...and thanks for the PR!

**Comment by creachadair** [comment]
> This created the creachadair-enhubbenate branch that I then converted to PR 324 (#324)... and that kicked off the two Travis-CI jobs running now. I'll merge shortly... and I guess we could close _this_ PR.
> 
> Please excuse my novice GitHub knowledge here...and thanks for the PR!

Whatever is easiest for you, I'm not picky about how it gets merged. 😄

**Comment by creachadair** [comment]
Since #324 is now merged, I'll close this.

**Pull request closed without merging**
